{application,inplace,
             [{modules,['Elixir.InPlace.Array','Elixir.InPlace.BitSet',
                        'Elixir.InPlace.BitUtils','Elixir.InPlace.Common',
                        'Elixir.InPlace.ExactCover',
                        'Elixir.InPlace.Examples.Josephus',
                        'Elixir.InPlace.Examples.Sudoku',
                        'Elixir.InPlace.Heap','Elixir.InPlace.HeapSort',
                        'Elixir.InPlace.LinkedList',
                        'Elixir.InPlace.PriorityQueue','Elixir.InPlace.Queue',
                        'Elixir.InPlace.SparseSet','Elixir.InPlace.Stack',
                        bit_vector]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"Mutable data structures"},
              {registered,[]},
              {vsn,"0.7.7"}]}.
